interface IJsonData{
    _id: string,
    area: string,
    below: string[],
    indicator: number,
    ius: string,
    rank: number,
    src: number,
    subgrp: number,
    top: string[],
    tp: string,
    trend: string,
    value: number,
    slugiddata: number,
    createdDate:string,
    lastModified:string,
    dKPIRSrs:boolean,
    dNITIRSrs:boolean,
    tps:string,
    dTHEMATICRSrs:boolean
}